# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-10 18:39
from __future__ import unicode_literals

from django.db import migrations, models
import utils.file_utils


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userprofile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to=utils.file_utils.get_image_file_path),
        ),
    ]
