export const OPEN_POST_MODAL = 'OPEN_POST_MODAL'
export const CLOSE_POST_MODAL = 'CLOSE_POST_MODAL'
export const OPEN_PROFILE_MODAL = 'OPEN_PROFILE_MODAL'
export const CLOSE_PROFILE_MODAL = 'CLOSE_PROFILE_MODAL'
