export const SIGN_OUT = 'SIGN_OUT'
export const RECEIVE_CURRENT_USER = 'RECEIVE_CURRENT_USER'
export const UPDATE_CURRENT_USER = 'UPDATE_CURRENT_USER'
export const RECEIVE_CURRENT_USER_PROFILE = 'RECEIVE_CURRENT_USER_PROFILE'
